name: Dump contexts

on: push

jobs:
  echo:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump variables
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF: ${{ github.ref }}
        run: echo "Event name $EVENT_NAME and ref $REF"
      - name: Env
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF: ${{ github.ref }}
          VAR_WITH_PLUS: ${{ secrets.VAR_WITH_PLUS }}
        run: env > text.tmp
      - name: File
        run: cat text.tmp
      - name: Outputs
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF: ${{ github.ref }}
          ROBOT: ${{ format('Hello {0} {1} {2} {3}', 'Hubot', 'the', 'friendly', 'robot') }}
        run: |
          echo "Event name $EVENT_NAME and ref $REF"
          echo "$ROBOT"
