name: Node CI

on: [push]

jobs:
  publish:
    env:
      NODE_VERSION: 12.x
    runs-on: ubuntu-latest

    publish-gpr:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
            node-version: 12.x
            registry-url: https://npm.pkg.github.com/
            scope: 'andersjanmyr'
        - run: npm ci
        - name: Publish
          if: branch == 'master'
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
