name: publish

on:
  push:
    branches:
      - master
jobs:
  publish:
    env:
      NODE_VERSION: 12.x
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: '@andersjanmyr'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        docker build -t docker.pkg.github.com/andersjanmyr/octodog/octodog:${{ github.sha }} .
        docker login docker.pkg.github.com -u andersjanmyr -p $GITHUB_TOKEN
        docker push docker.pkg.github.com/andersjanmyr/octodog/octodog:${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
